/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 starry_night_diorama_tilt_brush.glb --types
Files: starry_night_diorama_tilt_brush.glb [48.89MB] > gltf-transform metalrough, unlit, optimize (meshopt, webp) [7.19MB]
Author: george peaslee (https://sketchfab.com/georgepeaslee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starry-night-diorama-tilt-brush-3e0b5185d1f8435b993e1bad2f82928e
Title: Starry Night Diorama Tilt Brush
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CoarseBristles_geo_CoarseBristles_0: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_1: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_2: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_3: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_4: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_5: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_6: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_7: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_8: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_9: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_10: THREE.Mesh
    CoarseBristles_geo_CoarseBristles_0_11: THREE.Mesh
    FlatDeprecated_geo_FlatDeprecated_0: THREE.Mesh
    Wire_geo_Wire_0: THREE.Mesh
  }
  materials: {
    CoarseBristles: THREE.MeshBasicMaterial
    FlatDeprecated: THREE.MeshBasicMaterial
    Wire: THREE.MeshBasicMaterial
  }
}

/** Darkening curve on the vertex colours: 1 keeps white white, higher is darker. */
const DARKEN = 2.2

/** Pushes the darks and mid-tones down, once per geometry (useGLTF caches them). */
function darken(nodes: GLTFResult['nodes']) {
  for (const { geometry } of Object.values(nodes)) {
    const color = geometry.getAttribute('color')
    if (!color || geometry.userData.darkened) continue
    for (let i = 0; i < color.count; i++) {
      for (let c = 0; c < 3; c++) color.setComponent(i, c, color.getComponent(i, c) ** DARKEN)
    }
    color.needsUpdate = true
    geometry.userData.darkened = true
  }
}

export function StarryNight(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/starry_night_diorama_tilt_brush.glb') as unknown as GLTFResult
  darken(nodes)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0.geometry} material={materials.CoarseBristles} position={[-0.368, 2.287, -0.121]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.861} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_1.geometry} material={materials.CoarseBristles} position={[-0.449, 2.383, -0.113]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.881} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_2.geometry} material={materials.CoarseBristles} position={[-0.416, 1.99, 0.372]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.926} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_3.geometry} material={materials.CoarseBristles} position={[0.079, 1.71, 1.212]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.686} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_4.geometry} material={materials.CoarseBristles} position={[-1.246, 1.862, 1.711]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.644} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_5.geometry} material={materials.CoarseBristles} position={[-1.278, 1.878, 1.69]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.689} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_6.geometry} material={materials.CoarseBristles} position={[-1.261, 1.802, 1.719]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.651} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_7.geometry} material={materials.CoarseBristles} position={[-1.459, 1.816, 1.782]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.723} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_8.geometry} material={materials.CoarseBristles} position={[-1.571, 1.391, 0.874]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.44} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_9.geometry} material={materials.CoarseBristles} position={[-0.191, 1.207, 1.092]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.433} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_10.geometry} material={materials.CoarseBristles} position={[0.417, 1.552, 0.705]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.953} />
      <mesh geometry={nodes.CoarseBristles_geo_CoarseBristles_0_11.geometry} material={materials.CoarseBristles} position={[0.884, 1.509, 0.694]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.813} />
      <mesh geometry={nodes.FlatDeprecated_geo_FlatDeprecated_0.geometry} material={materials.FlatDeprecated} position={[-0.342, 1.444, 0.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.608} />
      <mesh geometry={nodes.Wire_geo_Wire_0.geometry} material={materials.Wire} position={[-0.089, 1.089, 1.186]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.024} />
    </group>
  )
}

useGLTF.preload('models/starry_night_diorama_tilt_brush.glb')
